### ISSUE TITLE
Default Magento Export file

### ISSUE THREAD

**Issue by turtlecreations** [semaio/Magento2-ConfigImportExport#13]
In the Export of an clean Magento installation, there are only an few settings included. I have an older installation of Magento 2, where I installed several plugins. These also contain settings that are exported. I would like to start over but import only the core Magento values. Is there an way (with an little hack) to generate an Magento file with all core config fields included? Than I can do an file compare and generate an file with only those core config settings but then from my previous installation.

Thanks in advance.

**Comment by therouv** [comment]
Hi @turtlecreations 
When using the export command you can define which paths from the configuration should be excluded. See [here](https://github.com/semaio/Magento2-ConfigImportExport/blob/develop/Command/ExportCommand.php#L77) (command) and [here](https://github.com/semaio/Magento2-ConfigImportExport/blob/develop/Model/Processor/ExportProcessor.php#L95) (implementation).

I'd suggest you exclude the settings of your custom plugins. You will then receive a file which only contain the core Magento values.

**Comment by tkn98** [comment]
@turtlecreations: I think this is non-trivial as the exported configuration is from the database store while the default values are from the XML files. Iterating over all XML files and extracting the values via xpath could be relatively straight forward, encoding as YAML is straight forward from array-structures and the pecl YAML extension. See https://gist.github.com/ktomk/a7690cc3353298eec609fdc1d76ad295 for a rudmentary script (here di.xml, not config.xml).
