### ISSUE TITLE
Can't install package due to composer conflicts.

### ISSUE THREAD

**Issue by kimpellikaan** [semaio/Magento2-ConfigImportExport#19]
### General

* Module version: 2.2
* Magento version: 2.2.0
* PHP version: 7.0.23

### Issue description
Can't install  due to composer conflicts. See dump:
```
Using version ^2.2 for semaio/magento2-configimportexport
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install semaio/magento2-configimportexport 2.2.2
    - Conclusion: don't install semaio/magento2-configimportexport 2.2.1
    - Conclusion: remove symfony/dependency-injection v3.3.10
    - Installation request for semaio/magento2-configimportexport ^2.2 -> satisfiable by semaio/magento2-configimportexport[2.2.0, 2.2.1, 2.2.2].
    - Conclusion: don't install symfony/dependency-injection v3.3.10
    - semaio/magento2-configimportexport 2.2.0 requires symfony/yaml ~2.0 -> satisfiable by symfony/yaml[2.0.4, 2.0.5, 2.0.6, 2.0.7, v2.0.10, v2.0.12, v2.0.13, v2.0.14, v2.0.15,
```

**Comment by barbazul** [comment]
Definitely not working with Magento 2.2

Also, look at this similar issue: https://github.com/netz98/n98-magerun2/pull/313

**Comment by turtlecreations** [comment]
In Magento 2.2.2 (with PHP 7.1) still issue's. Installation via composer:
....
 - Installation request for symfony/dependency-injection (locked at v3.4.4) -> satisfiable by symfony/dependency-injection[v3.4.4].

Symfony wants to downgrade some packages.

Installation via code dir does work for the config:data:export

But the config:data:import fails:

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Yaml' not found in /home//public_html/app/code/Semaio/ConfigImportExport/Model/File/Reader/YamlReader.php:23
Stack trace:
#0 /home//public_html/app/code/Semaio/ConfigImportExport/Model/Processor/ImportProcessor.php(100): Semaio\ConfigImportExport\Model\File\Reader\YamlReader->parse('config/store/ba...')
#1 /home//public_html/app/code/Semaio/ConfigImportExport/Model/Processor/ImportProcessor.php(74): Semaio\ConfigImportExport\Model\Processor\ImportProcessor->getConfigurationsFromFile('config/store/ba...')
#2 /home//public_html/app/code/Semaio/ConfigImportExport/Command/ImportCommand.php(129): Semaio\ConfigImportExport\Model\Processor\ImportProcessor->process()
#3 /home//public_html/vendor/symfony/console/Command/Command.php(242): Semaio\ConfigI in /home/public_html/app/code/Semaio/ConfigImportExport/Model/File/Reader/YamlReader.php on line 23
