### ISSUE TITLE
import fails from yaml file

### ISSUE THREAD

**Issue by jackjackde** [semaio/Magento2-ConfigImportExport#32]
Please make sure that you provide as much information as possible. If you have an example files, which reflect the issue, please make sure to attach them to the issue - thank you!

### General

* Module version: 3.0.0
* Magento version: 2.2.7
* PHP version: 7.1.25

### Issue description
At import, Yaml File Reader > yaml::parse return filepath instead of array. looks like wrong symfony/yaml version.
symfony/yaml version: 3.2.18
...

### Steps to reproduce

1. `bin/magento config:data:export` to export config
2. copy to base and dev folder (dev only custom parts)
3. `bin/magento config:data:import config/store dev`

![image](https://user-images.githubusercontent.com/2054008/53231990-6cc8da80-368a-11e9-822c-222048dcf124.png)

**Comment by DavidLambauer** [comment]
Can be closed. Fix was introduced lately.
