### ISSUE TITLE
Magento 2.4.4 and php 8.1 support

### ISSUE THREAD

**Issue by simonmaass** [semaio/Magento2-ConfigImportExport#42]
Please make sure that you provide as much information as possible. If you have an example files, which reflect the issue, please make sure to attach them to the issue - thank you!

### General

* Module version: 3.x
* Magento version: 2.4.4
* PHP version: 8.1.5

### Issue description

Any plans to update this module for magento 2.4.4 and php 8.1.x?

**Comment by therouv** [comment]
Hi @simonmaass I'm currently working on this. Expecting to release it within the next week or two :-)

**Comment by simonmaass** [comment]
hey @therouv - you have any eta for this? 🤗

**Comment by parlt** [comment]
@therouv Hi Please change "php": "^7.2", to  "php": ">=7.2" in composer.json the PHP 8.1 compatibility check says the code is ok for version 8.1

**Comment by parlt** [comment]
Please take a look at https://github.com/semaio/Magento2-ConfigImportExport/pull/43/files

**Comment by therouv** [comment]
@simonmaass Done!

**Comment by simonmaass** [comment]
thank you guys!
