### ISSUE TITLE
[Question] Differences with Magento 2 standard export / import

### ISSUE THREAD

**Issue by emmguyot-adscom** [semaio/Magento2-ConfigImportExport#46]
With Magento2, I can export the configuration with 
`bin/magento app:config:dump`

and I can import it with 
`bin/magento setup:upgrade`

Excluding the choice of the format, what are the main features that this module brings in comparaison to those commands ?

**Comment by peterjaap** [comment]
I had this question as well and as far as I can see the main benefit of this extension versus `app:config:dump` / `app:config:import` is that this extension supports multiple environments.

Saving config values in `app/etc/config.php` works only for one environment - you can't set nested environments. I've seen CI/CD setups where the pipeline would copy `app/etc/config_<environment>.php` to `app/etc/config.php` to allow for multiple environments. This extension makes that process a bit more streamlined, with the added benefit of generalization, cross-compatibility with other agencies/merchants using this and the multiple output formats.

**Comment by therouv** [comment]
Thanks for the question @emmguyot-adscom and your response @peterjaap. I've taken the liberty and used your response to write a dedicated section in the [README](https://github.com/semaio/Magento2-ConfigImportExport/blob/main/README.md) about why people should use this extension (see commit a5f2340)

**Comment by emmguyot-adscom** [comment]
I thank both of you for this answer.
