### ISSUE TITLE
Deprecated Functionality: preg_replace_callback(): Passing null to parameter

### ISSUE THREAD

**Issue by torhoehn** [semaio/Magento2-ConfigImportExport#54]
Please make sure that you provide as much information as possible. If you have an example files, which reflect the issue, please make sure to attach them to the issue - thank you!

### General

* Module version: 3.10.0
* Magento version: 2.4.5-p1
* PHP version: 8.1.11

### Issue description
```
In ErrorHandler.php line 62:

  Deprecated Functionality: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/html/ve
  ndor/semaio/magento2-configimportexport/Model/Resolver/EnvironmentVariableResolver.php on line 31
```

### Steps to reproduce

1. run config import with a value (that was exported before) like:
```
tax/defaults/postcode:
  default:
    0:
```

**Comment by ktomk** [comment]
any thoughts? compare  https://github.com/semaio/Magento2-ConfigImportExport/pull/55#issuecomment-1278148610  @peterjaap

**Comment by peterjaap** [comment]
@torhoehn seems like you have a null value there in the database. So it gets exported as an empty field, which casts back to null when importing it.

**Comment by peterjaap** [comment]
Proposed fix; `is_null($value) ? '' : $value` 

```
php > $value = false; var_dump(is_null($value) ? '' : $value);
php shell code:1:
bool(false)
php > $value = null; var_dump(is_null($value) ? '' : $value);
php shell code:1:
string(0) ""
php > $value = ''; var_dump(is_null($value) ? '' : $value);
php shell code:1:
string(0) ""
php > $value = 'test'; var_dump(is_null($value) ? '' : $value);
php shell code:1:
string(4) "test"
```

**Comment by therouv** [comment]
@torhoehn Thanks for reporting this. I'm looking into the issue and your PR #55

**Comment by peterjaap** [comment]
@therouv oh woops, there already was a PR!

I just made one too (similar fix) but with the unit test updated https://github.com/semaio/Magento2-ConfigImportExport/pull/57

**Comment by peterjaap** [comment]
@therouv I changed my PR to only the unit test; https://github.com/semaio/Magento2-ConfigImportExport/pull/58

**Comment by peterjaap** [comment]
@therouv didn't like the unit test? :D

**Comment by therouv** [comment]
@peterjaap Needed to fix some other unit tests as well, so I did it in one go instead of one more merge 😅
