### ISSUE TITLE
Greater control of export output directory via --filename parameter

### ISSUE THREAD

**Issue by bluec** [semaio/Magento2-ConfigImportExport#60]
First of all, thanks for this module; Zookal/HarrisStreet-ImpEx was one of my favourite and most-used M1 magerun tools so it is great to see it recreated and re-imagined for M2.

One thing I wonder is whether we can have greater control of the export directory using the `--filename` parameter. [Currently](https://github.com/semaio/Magento2-ConfigImportExport/blob/8d5f74590ebb969123325d956d56a4799ac445f0/Model/File/Writer/AbstractWriter.php#L201) it will always export to `var/Ymd_His` followed by either `config` or the value of the `--filename` parameter and then optionally the namespace.

This isn't very flexible. For example, for my workflow I like to keep a copy of the dumped export in git, but currently it always dumps to a new directory because we can't remove the `Ymd_His` part of the export path so this then requires a manual step to copy or move everything into a consistent directory. 

Also, a lesser issue than the timestamping is that I might not want the data in `var` at all but possibly somewhere else. Setting --filename on [HarrisStreet-ImpEx](https://github.com/Zookal/HarrisStreet-ImpEx/blob/707b67f78b81778e98faff7f1710a2266d81c48f/src/lib/n98-magerun/modules/Zookal_HarrisStreetImpex/src/HarrisStreet/CoreConfigData/Export.php#L125) provided complete run-time override of the full output directory path.

I appreciate that emulating the HarrisStreet-ImpEx behaviour and allowing to completely override the path using `--filename` would be a breaking change for existing workflows so this may not be a popular idea.

However, a simple solution to the timestamping with no breaking changes would be to add a `--timestamp (-t)` parameter which defaults to true and if set to false will remove the timestamp portion of the export path. For me personally this would be a huge improvement in usability and come with no cost that I can see.

What do you think? I could do a PR for the latter if it would be useful?

**Comment by therouv** [comment]
@bluec Thanks for your input. I would suggest the following changes:
* Remove the timestamp from the file name if `--filename` option was specified by user (doesn't make sense to keep the timestamp in this case).
* Adding a new `--filepath` option to specify where extension should write the file to.

Let me know what you think!

**Comment by bluec** [comment]
@therouv yes absolutely, I like the idea of getting rid of the timestamp because you're right it doesn't make sense and could always be added by the user when running the command e.g. ```--filename=`date +"%Y%m%d_%H%M%S"` ```

It's complicated a little because the current `--filename` implementation does actually allow a path to be given by including slashes, although obviously this path is currently only relative to `./var/timestamp_/` so not very useful.

This means the proposed `--filename` and `--filepath` options can both contain an element of the path so there is overlap and this may be slightly confusing.

Therefore do you think if we had both these options then the `--filename` should be strictly the filename and not allow any path component?

**Comment by bluec** [comment]
Just to follow this up...

If no options are given by the user I think it would be good practice to place the export files into a subdirectory of `./var/` to avoid littering the filesystem.

How about this with just the `--filename` option and no need for `--filepath`?:

| --filename | Output path |
| ------------- | ------------- |
|  | ./var/semaio/config_export/export.yml |
| my_filename | ./var/semaio/config_export/my_filename.yml |
| some/relative/path/ | ./some/relative/path/export.yml |
| some/relative/path/my_filename | ./some/relative/path/my_filename.yml |

If `--filePerNameSpace=y` is given then the final basename would be appended with the appropriate _namespace

I don't think providing for full absolute paths is necessary as it should be fair to assume that the export will be written somewhere within the project dir.

What do you think?

**Comment by bluec** [comment]
@therouv ignore all my waffle up there :) I have made a PR based on your suggestion which was much more elegant!

**Comment by therouv** [comment]
PR #62 is merged.
