### ISSUE TITLE
Empty directory throws error and breaks deployment

### ISSUE THREAD

**Issue by torhoehn** [semaio/Magento2-ConfigImportExport#70]
### General

* PHP version: 8.1
* Magento version: 2.4.6
* Module version: 4.1.0

### Issue description
During deployment we run `run('{{release_or_current_path}}/bin/magento config:data:import {{release_or_current_path}}/.config/store {{environment}}');`

The environment variable is set through GitLab CI Variables.

Following scenario:
If you have an empty base directory and yaml files inside prod directory, the deployment for any other environment, besides prod, without config files will fail.

What do you think about changing this behaviour?
https://github.com/semaio/Magento2-ConfigImportExport/blob/main/Model/Processor/ImportProcessor.php#L89

**Comment by therouv** [comment]
@torhoehn In my opinion, the `base` directory should never be empty because one might not want to manage all configuration settings for every environment. Especially since you can always override settings from `base` in an `environment` config file.

But I'd be more than happy to merge a PR that changes that behaviour.

**Comment by torhoehn** [comment]
I had the following scenario while introducing this module to a existing project:

1. install module
2. create directories
3. set base_url for dev environment

So in this scenario the base directory is empty. Later sure some config would be added here.

**Comment by therouv** [comment]
@torhoehn Thanks for the explanation. It definitely makes sense to change the behaviour in this case. Can you provide a PR please?

**Comment by torhoehn** [comment]
@therouv Yes, please provide feedback on #71.
