### ISSUE TITLE
Allow encryption of core config data

### ISSUE THREAD

**Issue by wilfriedwolf** [semaio/Magento2-ConfigImportExport#73]
Hi there,

I stumbled over a use case, where I need to import config data to a config field with `\Magento\Config\Model\Config\Backend\Encrypted` as a backend model.
While I could encrypt this field locally (same encryption key needed)  there are situations where you do not want to do so, especially in a kubernetes situation.

So I had the idea to resolve the data just like an env variable and just extended the module in a way to support substitution like:

```
'0': '%encrypt(%env(PAY_PAL_SECRET)%)%'
```

If you are interested, I could share...

Best regards,

Willi

**Comment by therouv** [comment]
@wilfriedwolf Sounds like this might be a great addition! Happy to merge a PR that adds this behavior.

**Comment by therouv** [comment]
Implemented in #74
